<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import math

In [2]:
X, Y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state = 0)
X_train, X_cv, Y_train, Y_cv = train_test_split(X_train, Y_train, test_size=0.3)

In [3]:
print(X_cv)

[[-1.29548643  0.42093955  0.04696382  0.0792216   0.20891604]
 [-0.6466714  -0.10720801  0.11643484  0.14071315 -0.44805596]
 [-0.87471418 -0.61370156  0.16909783  0.18219095 -1.03516269]
 ...
 [ 0.23263333  0.24367062  0.43482552  0.55666254 -1.13265111]
 [ 0.12084262 -0.08221712 -0.11956927 -0.1538085   0.29868972]
 [ 0.14241304 -1.37526811 -0.50505122 -0.69942701  0.39873757]]


### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [4]:
# you can write your code here
clf = SVC(gamma=0.001, C=100., kernel='rbf')
clf.fit(X_train, Y_train)

SVC(C=100.0, gamma=0.001)

In [5]:
intercept_train = clf.intercept_[0]
print(intercept_train)

3.2181721212162735


In [6]:
alpha_train = clf.dual_coef_[0]

In [7]:
y_pred_clf = clf.decision_function(X_cv)
print(y_pred_clf)
print(len(y_pred_clf))

[-0.38799984 -1.62143033 -2.74101189 ... -3.41768652  0.23102012
  1.2823461 ]
1050


In [8]:
support_indices = clf.support_

In [9]:
Y_temp = Y_train[support_indices]
X_temp = X_train[support_indices]

In [10]:
print(X_temp.shape)
print(Y_temp.shape)
print(X_cv.shape)
print(alpha_train.shape)

(469, 5)
(469,)
(1050, 5)
(469,)


In [11]:
def decision_function(X_cv):
    
    x_cv_pred=np.empty([1000,0])
    for i in X_cv:
        sum=0
        for j in range(0,len(X_temp)):
            k = np.exp(-0.001 * (np.dot(X_temp[j]-i, X_temp[j]-i)))
            sum += (alpha_train[j] * k)
            
        x_cv_pred=np.append(x_cv_pred,(sum+intercept_train))
    return x_cv_pred

In [12]:
def K(xi, xcv):
    gamma = 0.0001
    sum = 0
    for i in range(len(xi)):
        diff = abs(xi[i] - xcv[i])
        sum += math.exp(-gamma * diff**2)
        
    return sum

In [13]:
fcv = decision_function(X_cv)
print(fcv)
print(fcv.shape)

[-0.38799984 -1.62143033 -2.74101189 ... -3.41768652  0.23102012
  1.2823461 ]
(1050,)


In [14]:
y_pred_clf - fcv

array([0., 0., 0., ..., 0., 0., 0.])

In [15]:
ftest = decision_function(X_test)
print(ftest)
print(ftest.shape)

[-3.46148954  0.13255177 -1.64833109 ... -3.02145553 -3.12961766
 -1.53950159]
(1500,)


<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

In [16]:
pos = np.count_nonzero(Y_train == 1)
neg = np.count_nonzero(Y_train == 0)
yp = (pos+1) / (pos+2)
yn = 1 / (neg+2)
y_updated = np.where(Y_train==0,yn,yp)

print(y_updated.shape)

pos_cv = np.count_nonzero(Y_cv == 1)
neg_cv = np.count_nonzero(Y_cv == 0)
yp_cv = (pos_cv+1) / (pos_cv+2)
yn_cv = 1 / (neg_cv+2)
y_cv_updated = np.where(Y_cv==0,yn_cv,yp_cv)
y_cv_updated = y_cv_updated.astype('float')

print(y_cv_updated.shape)
print(y_cv_updated)

pos_test = np.count_nonzero(Y_test == 1)
neg_test = np.count_nonzero(Y_test == 0)
yp_test = (pos_test+1) / (pos_test+2)
yn_test = 1 / (neg_test+2)
y_test_updated = np.where(Y_test==0,yn_test,yp_test)

print(y_test_updated.shape)
print(y_test_updated)

(2450,)
(1050,)
[0.00134953 0.00134953 0.00134953 ... 0.00134953 0.00134953 0.99680511]
(1500,)
[0.00098328 0.00098328 0.00098328 ... 0.00098328 0.00098328 0.00098328]


In [17]:
def initialize_weights(dim):
    w = np.zeros_like(dim)
    b = 0
    return w,b

In [18]:
def sigmoid(z):
    return 1 / ( 1 + np.exp(-z) )

In [19]:
 def gradient_db(x,y,w,b):
    db = y - sigmoid(np.dot(w, x+b ) )
    return db

In [20]:
def gradient_dw(x,y,w,b,alpha,N):
    dw = x*( y - sigmoid(np.dot(w, x+b ) ) ) - ( ( alpha * w )/ N )
    return dw

In [21]:
def logloss(y_true,y_pred):
    '''In this function, we will compute log loss '''

    loss = 0
    n = len(y_true)
    n=2
    for i in range(0,n):
#         print(y_true[i], y_pred[i])
        loss += ( y_true[i] * math.log10(y_pred[i]) ) + (( 1 - y_true[i] )* math.log10( 1 - y_pred[i] ))
        
    loss = -1 * (1/n) * loss
    return loss

In [22]:
def train(X,Y,epochs,alpha,eta0):
    w,b = initialize_weights(X[0])
    y_pred = []
    loss_train = []
    loss_test = []
    N = len(X)
    for i in range(epochs):
        for j in range(N):
            ## batch size of 1
            x = X[j]
            y = Y[j]
            dw = gradient_dw(x,y,w,b,alpha,N)
            db = gradient_db(x,y,w,b)
            
            w += (eta0 * dw)
            b += (eta0 * db)
            y_pred_cv = sigmoid(np.dot(w.T, x.T) + b )
            y_pred.append(y_pred_cv)
        
        loss_train.append(logloss(Y,y_pred))
#         y_pred_test = sigmoid(np.dot(w.T, X_test.T) + b)
#         loss_test.append(logloss(y_test,y_test_updated))
    return w,b, loss_train, loss_test

In [23]:
alpha=0.0001
eta0=0.0001
N=len(fcv)
epochs=50
w,b, loss_train, loss_test=train(fcv,y_cv_updated,epochs,alpha,eta0)
print("weight:", w)
print("intercept:", b)

weight: 1.2234896642037565
intercept: -0.13413200738785755


In [24]:
alpha=0.001
eta0=0.0001
N=len(ftest)
epochs=50
w,b, loss_train, loss_test=train(ftest,y_test_updated,epochs,alpha,eta0)
print("weight:", w)
print("intercept:", b)

weight: 1.4000999364229088
intercept: -0.027487213803510525


__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm
